name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: api_ml
    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_ID }} ${{ secrets.DOCKER_HOST }} --password-stdin
        docker build --pull --no-cache -t ${{ secrets.DOCKER_IMAGE }} .
        docker push ${{ secrets.DOCKER_IMAGE }}

